### ISSUE TITLE
ConcurrentModificationException and game hangup

### ISSUE THREAD

**Issue by Sytm** [wagyourtail/WagYourMinimap#5]
```
[14:59:41] [pool-7-thread-2/ERROR]: Uncaught exception in thread "pool-7-thread-2"
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
	at xyz.wagyourtail.minimap.chunkdata.ChunkData.serializeBlocks(ChunkData.java:164) ~[wagyourminimap-1.19-1.0.8-fabric.jar:?]
	at xyz.wagyourtail.minimap.chunkdata.cache.ZipCacher.writeToZip(ZipCacher.java:98) ~[wagyourminimap-1.19-1.0.8-fabric.jar:?]
	at xyz.wagyourtail.minimap.chunkdata.cache.ZipCacher.saveChunk(ZipCacher.java:93) ~[wagyourminimap-1.19-1.0.8-fabric.jar:?]
	at xyz.wagyourtail.minimap.chunkdata.cache.CacheManager.saveChunk(CacheManager.java:131) ~[wagyourminimap-1.19-1.0.8-fabric.jar:?]
	at xyz.wagyourtail.minimap.chunkdata.ChunkData.save(ChunkData.java:221) ~[wagyourminimap-1.19-1.0.8-fabric.jar:?]
	at xyz.wagyourtail.minimap.map.MapServer.lambda$addToSaveQueue$0(MapServer.java:36) ~[wagyourminimap-1.19-1.0.8-fabric.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15:00:57] [Server thread/INFO]: Saving and pausing game...
[15:00:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival]'/minecraft:overworld
[15:00:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival]'/minecraft:the_nether
[15:00:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival]'/minecraft:the_end
[15:01:39] [Server thread/INFO]: Sytm hat den Fortschritt [Verzauberer] erzielt
[15:01:39] [Render thread/INFO]: [CHAT] Sytm hat den Fortschritt [Verzauberer] erzielt
[15:01:39] [Render thread/INFO]: Loaded 414 advancements
[15:02:39] [Server thread/INFO]: Saving and pausing game...
[15:02:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival]'/minecraft:overworld
[15:02:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival]'/minecraft:the_nether
[15:02:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival]'/minecraft:the_end
[15:02:40] [Render thread/INFO]: exiting MapServer{server_slug='UNKNOWN_SERVER_NAME'}
[15:02:40] [Render thread/INFO]: Minimap Saving Chunks, (Remaining: 2)
Process crashed with status 9
```
Just wanted to close my local survival world and then the entire game began to hang but did not instantly crash (probably at the log entry `Minimap Saving Chunks, (Remaining: 2)`).

I guess it maybe is connected to the previous error.

Running Minecraft 1.19, Fabric Loader 0.14.8, Fabric API 0.58.0, ArchitecturyAPI 5.10.33 launched with PolyMC on Linux

**Comment by wagyourtail** [comment]
reopen if this still happens with https://github.com/wagyourtail/WagYourMinimap/actions/runs/2741913110 or a later version

**Comment by Sytm** [comment]
It's fixed now, thanks :+1:
