### ISSUE TITLE
Random Hang on player join/dimention switch/death. (each time "Loading Terrain..." happens)

### ISSUE THREAD

**Issue by pog5** [wagyourtail/WagYourMinimap#7]
Title says it all. Nothing unusual gets logged to the Console.
Using Latest 1.18.2 Fabric version that's on Modrinth.

**Comment by QuImUfu** [comment]
This is caused by a deadlock. here the relevant VisualVM output:
```
Found one Java-level deadlock:
=============================
"Render thread":
  waiting to lock monitor 0x00007feed8003640 (object 0x000000071377d1a0, a xyz.wagyourtail.minimap.chunkdata.cache.CacheManager),
  which is held by "pool-3-thread-1"

"pool-3-thread-1":
  waiting to lock monitor 0x00007feed8008890 (object 0x000000078e01e750, a xyz.wagyourtail.minimap.chunkdata.ChunkData),
  which is held by "pool-2-thread-4"

"pool-2-thread-4":
  waiting to lock monitor 0x00007feed8003640 (object 0x000000071377d1a0, a xyz.wagyourtail.minimap.chunkdata.cache.CacheManager),
  which is held by "pool-3-thread-1"

Java stack information for the threads listed above:
===================================================
"Render thread":
        at xyz.wagyourtail.minimap.chunkdata.cache.CacheManager.loadChunk(CacheManager.java:89)
        - waiting to lock <0x000000071377d1a0> (a xyz.wagyourtail.minimap.chunkdata.cache.CacheManager)
        at xyz.wagyourtail.minimap.chunkdata.ChunkLocation.get(ChunkLocation.java:53)
        at xyz.wagyourtail.minimap.map.image.ImageStrategy.getImage(ImageStrategy.java:16)
        - locked <0x00000007136c6028> (a xyz.wagyourtail.minimap.map.image.VanillaMapImageStrategy)
        at xyz.wagyourtail.minimap.client.gui.AbstractMapRenderer.bindChunkTex(AbstractMapRenderer.java:193)
        at xyz.wagyourtail.minimap.client.gui.AbstractMapRenderer.bindLayer(AbstractMapRenderer.java:185)
        at xyz.wagyourtail.minimap.client.gui.AbstractMapRenderer.drawChunkBatchTex(AbstractMapRenderer.java:173)
        at xyz.wagyourtail.minimap.client.gui.AbstractMapRenderer.drawChunk(AbstractMapRenderer.java:147)
        at xyz.wagyourtail.minimap.client.gui.AbstractMapRenderer.drawPartialChunk(AbstractMapRenderer.java:139)
        at xyz.wagyourtail.minimap.client.gui.hud.map.AbstractMinimapRenderer.renderMinimap(AbstractMinimapRenderer.java:214)
        at xyz.wagyourtail.minimap.client.gui.hud.map.AbstractMinimapRenderer.render(AbstractMinimapRenderer.java:131)
        at xyz.wagyourtail.minimap.client.gui.hud.InGameHud.render(InGameHud.java:20)
        at xyz.wagyourtail.minimap.client.WagYourMinimapClient.lambda$init$0(WagYourMinimapClient.java:95)
        at xyz.wagyourtail.minimap.client.WagYourMinimapClient$$Lambda$7092/0x0000000801126138.renderHud(Unknown Source)
        at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerClient$7(EventHandlerImpl.java:60)
        at dev.architectury.event.fabric.EventHandlerImpl$$Lambda$4884/0x0000000800cf4228.onHudRender(Unknown Source)
        at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
        at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback$$Lambda$4883/0x0000000800cf4000.onHudRender(Unknown Source)
        at net.minecraft.class_329.handler$dde000$render(class_329.java:3996)
        at net.minecraft.class_329.method_1753(class_329.java:393)
        at net.minecraft.class_757.method_3192(class_757.java:862)
        at net.minecraft.class_310.method_1523(class_310.java:1177)
        at net.minecraft.class_310.method_1514(class_310.java:768)
        at net.minecraft.client.main.Main.method_44604(Main.java:244)
        at net.minecraft.client.main.Main.main(Main.java:51)
        at java.lang.invoke.LambdaForm$DMH/0x0000000800368000.invokeStaticInit(java.base@17.0.4/LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$MH/0x0000000800368400.invokeExact_MT(java.base@17.0.4/LambdaForm$MH)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.4/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.4/NativeMethodAccessorImpl.java:77)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.4/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@17.0.4/Method.java:568)
        at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
        at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
        at org.multimc.EntryPoint.listen(EntryPoint.java:143)
        at org.multimc.EntryPoint.main(EntryPoint.java:34)
"pool-3-thread-1":
        at xyz.wagyourtail.minimap.chunkdata.cache.ZipCacher.writeToZip(ZipCacher.java:98)
        - waiting to lock <0x000000078e01e750> (a xyz.wagyourtail.minimap.chunkdata.ChunkData)
        - locked <0x000000071377e870> (a xyz.wagyourtail.minimap.chunkdata.cache.ZipCacher)
        at xyz.wagyourtail.minimap.chunkdata.cache.ZipCacher.saveChunk(ZipCacher.java:93)
        - locked <0x000000071377e870> (a xyz.wagyourtail.minimap.chunkdata.cache.ZipCacher)
        at xyz.wagyourtail.minimap.chunkdata.cache.CacheManager.saveChunk(CacheManager.java:131)
        - locked <0x000000071377d1a0> (a xyz.wagyourtail.minimap.chunkdata.cache.CacheManager)
        at xyz.wagyourtail.minimap.chunkdata.ChunkData.save(ChunkData.java:220)
        at xyz.wagyourtail.minimap.chunkdata.ChunkData$$Lambda$12247/0x0000000801917d08.run(Unknown Source)
        at xyz.wagyourtail.minimap.map.MapServer.lambda$addToSaveQueue$0(MapServer.java:36)
        at xyz.wagyourtail.minimap.map.MapServer$$Lambda$12248/0x0000000801918000.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.4/ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.4/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@17.0.4/Thread.java:833)
"pool-2-thread-4":
        at xyz.wagyourtail.minimap.chunkdata.cache.CacheManager.loadChunk(CacheManager.java:89)
        - waiting to lock <0x000000071377d1a0> (a xyz.wagyourtail.minimap.chunkdata.cache.CacheManager)
        at xyz.wagyourtail.minimap.chunkdata.ChunkLocation.get(ChunkLocation.java:53)
        at xyz.wagyourtail.minimap.chunkdata.updater.SurfaceDataUpdater.loadFromChunk(SurfaceDataUpdater.java:100)
        at xyz.wagyourtail.minimap.chunkdata.updater.SurfaceDataUpdater.lambda$onLoadChunk$0(SurfaceDataUpdater.java:40)
        at xyz.wagyourtail.minimap.chunkdata.updater.SurfaceDataUpdater$$Lambda$12231/0x000000080190b8c0.onChunkUpdate(Unknown Source)
        at xyz.wagyourtail.minimap.chunkdata.updater.AbstractChunkDataUpdater.lambda$updateChunk$0(AbstractChunkDataUpdater.java:62)
        at xyz.wagyourtail.minimap.chunkdata.updater.AbstractChunkDataUpdater$$Lambda$12244/0x0000000801917418.apply(Unknown Source)
        at xyz.wagyourtail.minimap.chunkdata.ChunkData.lambda$computeData$1(ChunkData.java:184)
        at xyz.wagyourtail.minimap.chunkdata.ChunkData$$Lambda$12245/0x0000000801917660.apply(Unknown Source)
        at java.util.HashMap.compute(java.base@17.0.4/HashMap.java:1316)
        at xyz.wagyourtail.minimap.chunkdata.ChunkData.computeData(ChunkData.java:184)
        - locked <0x000000078e01e750> (a xyz.wagyourtail.minimap.chunkdata.ChunkData)
        at xyz.wagyourtail.minimap.chunkdata.updater.AbstractChunkDataUpdater.lambda$updateChunk$1(AbstractChunkDataUpdater.java:60)
        - locked <0x000000078e01e750> (a xyz.wagyourtail.minimap.chunkdata.ChunkData)
        at xyz.wagyourtail.minimap.chunkdata.updater.AbstractChunkDataUpdater$$Lambda$12232/0x000000080190bae8.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.4/ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.4/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@17.0.4/Thread.java:833)

Found 1 deadlock.
```

**Comment by wagyourtail** [comment]
thank you, I'll look into it shortly

**Comment by wagyourtail** [comment]
let me know if that didn't work. you can grab a beta build for it at https://github.com/wagyourtail/WagYourMinimap/actions/runs/3262272020 (1.19.2)
