### ISSUE TITLE
Broken on 1.19.2 

### ISSUE THREAD

**Issue by cleonyc** [wagyourtail/WagYourMinimap#8]
Using latest minecraft 1.19.2 and latest WagYourMinimap. 
Haven't tried debugging past this point, but on launch I was presented with this error:
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'WagYourMinimap' (wagyourminimap) 1.0.10+1.19.1-fabric with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'WagYourMinimap' (wagyourminimap) 1.0.10+1.19.1-fabric requires version 1.19.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
```

**Comment by alikindsys** [comment]
@wagyourtail has updated the mod on HEAD, at least it seems. They probably forgot to release it or are working on adding more stuff before publishing it tho.
